[book]
authors = ["Pavel Perestoronin"]
multilingual = false
src = "book"
title = "bestmobabot"

[build]
build-dir = "docs"
create-missing = false

[output.html]
curly-quotes = true
google-analytics = "UA-65034198-8"
git-repository-url = "https://github.com/eigenein/bestmobabot"
git-repository-icon = "fa-code-fork"
