from typing import NewType

ClanID = NewType('ClanID', str)
ConsumableID = NewType('ConsumableID', str)
ExpeditionID = NewType('ExpeditionID', str)
ExpeditionStatus = NewType('ExpeditionStatus', int)
Experience = NewType('Experience', int)
Gold = NewType('Gold', int)
HeroID = NewType('HeroID', str)
LetterID = NewType('LetterID', str)
QuestID = NewType('QuestID', str)
QuestState = NewType('QuestState', int)
Stamina = NewType('Stamina', int)
StarMoney = NewType('StarMoney', int)
UserID = NewType('UserID', str)
